title: UO Splash
description: Website for UO Splash! Educational Outreach Program
theme: just-the-docs

url: https://uosplash.github.io

aux_links:
  Template Repository: https://github.com/uosplash/uosplash
