title: UO Splash
description: Website for UO Splash! Educational Outreach Program
remote_theme: just-the-docs
color_scheme: uo

url: https://uosplash.github.io

aux_links:
  Template Repository: https://github.com/uosplash/uosplash

  plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
