title: UO Splash!
description: Website for UO Splash Educational Outreach Program
theme: just-the-docs
color_theme: uo

url: https://uosplash.github.io/

aux_links:
  Contact Us: mailto:uosplash@gmail.com
